"""add ondelete property

Revision ID: 1a77bf5dba0e
Revises: 72068a6a492e
Create Date: 2025-04-01 05:45:48.085501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a77bf5dba0e'
down_revision: Union[str, None] = '72068a6a492e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('applicants_user_id_fkey', 'applicants', type_='foreignkey')
    op.create_foreign_key(None, 'applicants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('edu_workers_user_id_fkey', 'edu_workers', type_='foreignkey')
    op.create_foreign_key(None, 'edu_workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('employers_user_id_fkey', 'employers', type_='foreignkey')
    op.create_foreign_key(None, 'employers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.create_foreign_key('employers_user_id_fkey', 'employers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'edu_workers', type_='foreignkey')
    op.create_foreign_key('edu_workers_user_id_fkey', 'edu_workers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.create_foreign_key('applicants_user_id_fkey', 'applicants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
