"""add PK and FK indexes

Revision ID: 2069eb021568
Revises: 26c2cd34b2c2
Create Date: 2025-04-12 15:06:44.239414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2069eb021568'
down_revision: Union[str, None] = '26c2cd34b2c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_employment_formats_id'), 'employment_formats', ['id'], unique=False)
    op.create_index(op.f('ix_employment_schedules_id'), 'employment_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_employment_types_id'), 'employment_types', ['id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_vacancies_id'), 'vacancies', ['id'], unique=False)
    op.create_index(op.f('ix_vacancies_formats_format_id'), 'vacancies_formats', ['format_id'], unique=False)
    op.create_index(op.f('ix_vacancies_formats_vacancy_id'), 'vacancies_formats', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_vacancies_schedules_schedule_id'), 'vacancies_schedules', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_vacancies_schedules_vacancy_id'), 'vacancies_schedules', ['vacancy_id'], unique=False)
    op.create_index(op.f('ix_vacancies_types_type_id'), 'vacancies_types', ['type_id'], unique=False)
    op.create_index(op.f('ix_vacancies_types_vacancy_id'), 'vacancies_types', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancies_types_vacancy_id'), table_name='vacancies_types')
    op.drop_index(op.f('ix_vacancies_types_type_id'), table_name='vacancies_types')
    op.drop_index(op.f('ix_vacancies_schedules_vacancy_id'), table_name='vacancies_schedules')
    op.drop_index(op.f('ix_vacancies_schedules_schedule_id'), table_name='vacancies_schedules')
    op.drop_index(op.f('ix_vacancies_formats_vacancy_id'), table_name='vacancies_formats')
    op.drop_index(op.f('ix_vacancies_formats_format_id'), table_name='vacancies_formats')
    op.drop_index(op.f('ix_vacancies_id'), table_name='vacancies')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_employment_types_id'), table_name='employment_types')
    op.drop_index(op.f('ix_employment_schedules_id'), table_name='employment_schedules')
    op.drop_index(op.f('ix_employment_formats_id'), table_name='employment_formats')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    # ### end Alembic commands ###
