"""add resume table

Revision ID: 22d7b0560dea
Revises: 5d43403feb84
Create Date: 2025-04-15 12:33:05.384998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22d7b0560dea'
down_revision: Union[str, None] = '5d43403feb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=120), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('salary', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_id'), 'resume', ['id'], unique=False)
    op.create_index(op.f('ix_resume_user_id'), 'resume', ['user_id'], unique=True)
    op.create_table('resume_formats',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('format_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['format_id'], ['employment_formats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_id', 'format_id')
    )
    op.create_index(op.f('ix_resume_formats_format_id'), 'resume_formats', ['format_id'], unique=False)
    op.create_index(op.f('ix_resume_formats_resume_id'), 'resume_formats', ['resume_id'], unique=False)
    op.create_table('resume_types',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['type_id'], ['employment_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_id', 'type_id')
    )
    op.create_index(op.f('ix_resume_types_resume_id'), 'resume_types', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_types_type_id'), 'resume_types', ['type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_types_type_id'), table_name='resume_types')
    op.drop_index(op.f('ix_resume_types_resume_id'), table_name='resume_types')
    op.drop_table('resume_types')
    op.drop_index(op.f('ix_resume_formats_resume_id'), table_name='resume_formats')
    op.drop_index(op.f('ix_resume_formats_format_id'), table_name='resume_formats')
    op.drop_table('resume_formats')
    op.drop_index(op.f('ix_resume_user_id'), table_name='resume')
    op.drop_index(op.f('ix_resume_id'), table_name='resume')
    op.drop_table('resume')
    # ### end Alembic commands ###
