"""add company address and inn

Revision ID: 26c2cd34b2c2
Revises: 89a4513965e7
Create Date: 2025-04-10 18:33:49.479024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c2cd34b2c2'
down_revision: Union[str, None] = '89a4513965e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('inn', sa.String(length=12), nullable=True))
    op.add_column('companies', sa.Column('address', sa.String(length=120), nullable=True))
    op.create_unique_constraint(None, 'companies', ['inn'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'companies', type_='unique')
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'inn')
    # ### end Alembic commands ###
