"""increase description fields on models

Revision ID: 2af7b033bec6
Revises: f6352a966bbe
Create Date: 2025-05-26 15:36:51.080931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2af7b033bec6'
down_revision: Union[str, None] = 'f6352a966bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'description',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=5000),
               existing_nullable=True)
    op.alter_column('negotiations', 'employer_description',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('recommendations', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=False)
    op.alter_column('resume', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('resume', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('recommendations', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('negotiations', 'employer_description',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=150),
               existing_nullable=True)
    op.alter_column('companies', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###
