"""update roles tables associations

Revision ID: 50eb3d8320e8
Revises: 8cba4e189d19
Create Date: 2025-04-02 14:24:00.197050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50eb3d8320e8'
down_revision: Union[str, None] = '8cba4e189d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'applicants', 'edu_levels', ['edu_level_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'applicants', 'edu_institutions', ['edu_institution_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'edu_workers', 'edu_institutions', ['edu_institution_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'employers', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employers', type_='foreignkey')
    op.drop_constraint(None, 'edu_workers', type_='foreignkey')
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    op.drop_constraint(None, 'applicants', type_='foreignkey')
    # ### end Alembic commands ###
