"""add negotiations table

Revision ID: 53b408c4bf44
Revises: 2069eb021568
Create Date: 2025-04-12 15:55:03.428989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53b408c4bf44'
down_revision: Union[str, None] = '2069eb021568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vacancy_id', 'applicant_id', name='uix_negotiation_vacancy_applicant')
    )
    op.create_index(op.f('ix_negotiations_applicant_id'), 'negotiations', ['applicant_id'], unique=False)
    op.create_index(op.f('ix_negotiations_id'), 'negotiations', ['id'], unique=False)
    op.create_index(op.f('ix_negotiations_vacancy_id'), 'negotiations', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiations_vacancy_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_id'), table_name='negotiations')
    op.drop_index(op.f('ix_negotiations_applicant_id'), table_name='negotiations')
    op.drop_table('negotiations')
    # ### end Alembic commands ###
