"""add roles tables

Revision ID: 72068a6a492e
Revises: 3a5039296f33
Create Date: 2025-03-27 16:55:39.057076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72068a6a492e'
down_revision: Union[str, None] = '3a5039296f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edu_institution_id', sa.Integer(), nullable=True),
    sa.Column('edu_level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('edu_workers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('edu_institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('employers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employers')
    op.drop_table('edu_workers')
    op.drop_table('applicants')
    # ### end Alembic commands ###
