"""add applicant edu book number field

Revision ID: 72fd85e86f7b
Revises: bf101a5385a3
Create Date: 2025-04-17 18:42:53.504131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72fd85e86f7b'
down_revision: Union[str, None] = 'bf101a5385a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('edu_number', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_applicants_edu_number'), 'applicants', ['edu_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applicants_edu_number'), table_name='applicants')
    op.drop_column('applicants', 'edu_number')
    # ### end Alembic commands ###
