"""add vacancy author_id

Revision ID: 7be62b307542
Revises: 53b408c4bf44
Create Date: 2025-04-14 12:10:38.624390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be62b307542'
down_revision: Union[str, None] = '53b408c4bf44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('author_id', sa.Integer(), nullable=True))

    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE vacancies v
        SET author_id = (
            SELECT e.user_id
            FROM employers e
            WHERE e.company_id = v.company_id
            ORDER BY e.user_id
            LIMIT 1
        )
    """))

    op.alter_column('vacancies', 'author_id', nullable=False)
    op.create_index(op.f('ix_vacancies_author_id'), 'vacancies', ['author_id'], unique=False)
    op.create_foreign_key(None, 'vacancies', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_index(op.f('ix_vacancies_author_id'), table_name='vacancies')
    op.drop_column('vacancies', 'author_id')
    # ### end Alembic commands ###
