"""Fix vacancy salary orm type

Revision ID: 89a4513965e7
Revises: 50eb3d8320e8
Create Date: 2025-04-05 18:34:40.863508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89a4513965e7'
down_revision: Union[str, None] = '50eb3d8320e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('salary', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'salary')
    # ### end Alembic commands ###
