"""append users fields

Revision ID: bf101a5385a3
Revises: c40fc4c96a6c
Create Date: 2025-04-17 18:21:23.253578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf101a5385a3'
down_revision: Union[str, None] = 'c40fc4c96a6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('edu_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_location_id'), 'users', ['location_id'], unique=False)
    op.create_foreign_key(None, 'users', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_location_id'), table_name='users')
    op.drop_column('users', 'location_id')
    op.drop_column('users', 'sex')
    op.drop_column('applicants', 'edu_status')
    # ### end Alembic commands ###
