"""add recommendations_table

Revision ID: c40fc4c96a6c
Revises: 22d7b0560dea
Create Date: 2025-04-15 17:42:45.917628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c40fc4c96a6c'
down_revision: Union[str, None] = '22d7b0560dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_applicant_id'), 'recommendations', ['applicant_id'], unique=True)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('proof_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('download_name', sa.String(length=256), nullable=False),
    sa.Column('real_name', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proof_documents_id'), 'proof_documents', ['id'], unique=False)
    op.create_index(op.f('ix_proof_documents_recommendation_id'), 'proof_documents', ['recommendation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proof_documents_recommendation_id'), table_name='proof_documents')
    op.drop_index(op.f('ix_proof_documents_id'), table_name='proof_documents')
    op.drop_table('proof_documents')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_applicant_id'), table_name='recommendations')
    op.drop_table('recommendations')
    # ### end Alembic commands ###
