"""add vacancy location and work_hours fields

Revision ID: f6352a966bbe
Revises: 72fd85e86f7b
Create Date: 2025-05-04 17:12:10.334830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6352a966bbe'
down_revision: Union[str, None] = '72fd85e86f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('work_hours', sa.String(length=50), nullable=True))
    op.add_column('vacancies', sa.Column('location_id', sa.Integer(), nullable=True))
    op.alter_column('vacancies', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=5000),
               existing_nullable=False)
    op.create_index(op.f('ix_vacancies_location_id'), 'vacancies', ['location_id'], unique=False)
    op.create_foreign_key(None, 'vacancies', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_index(op.f('ix_vacancies_location_id'), table_name='vacancies')
    op.alter_column('vacancies', 'description',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.drop_column('vacancies', 'location_id')
    op.drop_column('vacancies', 'work_hours')
    # ### end Alembic commands ###
